export const byId = (id) => document.getElementById(id);
const dom = {
  drawerMenu: byId('drawerMenu'),
  drawerBackdrop: byId('drawerBackdrop'),
  openDrawerSidebar: byId('openDrawerSidebar'),
  closeDrawer: byId('closeDrawer'),
  saveStatus: byId('saveStatus'),
  drawerThemeToggle: byId('drawerThemeToggle'),
  themeLabel: byId('themeLabel'),
  sidebarNavButtons: [...document.querySelectorAll('.sidebar [data-section]')],
  financeDrawerButton: byId('openFinanceSection'),
  inventorySection: byId('inventorySection'),
  financeModal: byId('financeModal'),
  closeFinanceModal: byId('closeFinanceModal'),
  financeSettingsModal: byId('financeSettingsModal'),
  closeFinanceSettings: byId('closeFinanceSettings'),
  financeTabsNav: byId('financeTabsNav'),
  financeTabEntries: byId('financeTabEntries'),
  financeTabRecurring: byId('financeTabRecurring'),
  financeTabSummary: byId('financeTabSummary'),
  financeTabApi: byId('financeTabApi'),
  apartmentSearch: byId('apartmentSearch'),
  apartmentName: byId('apartmentName'),
  apartmentsList: byId('apartmentsList'),
  pageTitle: byId('pageTitle'),
  linenList: byId('linenList'),
  guestList: byId('guestList'),
  statsGrid: byId('statsGrid'),
  dailyUsage: byId('dailyUsage'),
  setUsage: byId('setUsage'),
  coverageList: byId('coverageList'),
  historyApartmentFilter: byId('historyApartmentFilter'),
  historyModalList: byId('historyModalList'),
  purchaseRequestsList: byId('purchaseRequestsList'),
  autoRequestToggle: byId('autoRequestToggle'),
  purchaseApartmentSelect: byId('purchaseApartmentSelect'),
  purchaseApartmentHint: byId('purchaseApartmentHint'),
  purchaseItemsWrap: byId('purchaseItemsWrap'),
  deductionSettings: byId('deductionSettings'),
  setSettings: byId('setSettings'),
  financeApartmentFilter: byId('financeApartmentFilter'),
  financeTypeFilter: byId('financeTypeFilter'),
  financeMonthFilter: byId('financeMonthFilter'),
  financeOnlyPending: byId('financeOnlyPending'),
  financeSummary: byId('financeSummary'),
  financeByApartment: byId('financeByApartment'),
  financeEntriesList: byId('financeEntriesList'),
  recurringExpensesList: byId('recurringExpensesList'),
  financeWebhookEndpoint: byId('financeWebhookEndpoint'),
  financeLastSync: byId('financeLastSync'),
  financeAddEntryBtn: byId('financeAddEntryBtn'),
  financeAddRecurringBtn: byId('financeAddRecurringBtn'),
  financePullBookingsBtn: byId('financePullBookingsBtn'),
  financeOpenWebhookHelpBtn: byId('financeOpenWebhookHelpBtn'),
  financeEntryApartment: byId('financeEntryApartment'),
  financeEntryType: byId('financeEntryType'),
  financeEntryCategory: byId('financeEntryCategory'),
  financeEntryTitle: byId('financeEntryTitle'),
  financeEntryAmount: byId('financeEntryAmount'),
  financeEntryDate: byId('financeEntryDate'),
  financeEntryNotes: byId('financeEntryNotes'),
  financeEntrySource: byId('financeEntrySource'),
  saveFinanceEntry: byId('saveFinanceEntry'),
  cancelFinanceEntry: byId('cancelFinanceEntry'),
  recurringApartment: byId('recurringApartment'),
  recurringTitle: byId('recurringTitle'),
  recurringCategory: byId('recurringCategory'),
  recurringAmount: byId('recurringAmount'),
  recurringDayOfMonth: byId('recurringDayOfMonth'),
  recurringStartDate: byId('recurringStartDate'),
  recurringEndDate: byId('recurringEndDate'),
  recurringNotes: byId('recurringNotes'),
  saveRecurringExpense: byId('saveRecurringExpense'),
  cancelRecurringExpense: byId('cancelRecurringExpense'),
  financeWebhookExample: byId('financeWebhookExample'),
  closeFinanceWebhookModal: byId('closeFinanceWebhookModal'),

  // ─── Компактный auth-виджет в правом верхнем углу ────────────────────────
  // Кнопка-слово: показывает "Меню" гостю и "Выход" вошедшему пользователю.
  // Выпадающее окошко с формой входа открывается только в режиме "гость".
  authCorner: byId('authCorner'),
  authCornerBtn: byId('authCornerBtn'),
  authDropdown: byId('authDropdown'),

  // Поля и кнопки внутри выпадающего окошка
  authBarEmail: byId('authBarEmail'),
  authBarPassword: byId('authBarPassword'),
  authBarToggle: byId('authBarToggle'),
  authBarSignIn: byId('authBarSignIn'),
  authBarSignUp: byId('authBarSignUp'),
  authBarMsg: byId('authBarMsg'),
  authBarUserEmail: byId('authBarUserEmail'),
  authBarStorageBadge: byId('authBarStorageBadge'),

  // ─── Интеграция с RealtyCalendar ────────────────────────────────
  // Блок в модалке "Настройки и интеграции".
  rcStatusBox:           byId('rcStatusBox'),
  rcAgencyIdInput:       byId('rcAgencyIdInput'),
  rcSaveBtn:             byId('rcSaveBtn'),
  rcDisconnectBtn:       byId('rcDisconnectBtn'),
  rcRefreshBtn:          byId('rcRefreshBtn'),
  rcWebhookUrl:          byId('rcWebhookUrl'),
  rcCopyWebhookBtn:      byId('rcCopyWebhookBtn'),
  rcLogList:             byId('rcLogList'),
  rcMsg:                 byId('rcMsg'),

  // Поле realty_id в форме переименования квартиры
  apartmentRealtyId:     byId('apartmentRealtyId'),
  saveApartmentRealtyId: byId('saveApartmentRealtyId'),
};
export default dom;
