import dom from './dom.js';
import { normalizeRealtyCalendarBooking, syncRealtyCalendarBookings } from './api.js';
import { addFinanceEntry, addRecurringRule, ensureFinanceGeneratedForCurrentMonth, importBookingsToFinance, monthKey } from './finance.js';
import { closeDrawer, closeModal, openDrawer, openModal, render, setStatus } from './render.js';
import { currentApartment, updateState } from './state.js';
import { saveToBrowser } from './storage.js';

async function rerender(statusText = 'Сохранено') { ensureFinanceGeneratedForCurrentMonth(); render(); await saveToBrowser(setStatus, true); setStatus(statusText); }
function bindSectionNav() { dom.sidebarNavButtons.forEach((button) => { button.addEventListener('click', async () => { updateState((state) => { state.ui.activeSection = button.dataset.section; }); await rerender(button.dataset.section === 'finance' ? 'Открыт финансовый учет' : 'Открыт складской раздел'); closeDrawer(); }); }); }
function bindTheme() { dom.drawerThemeToggle?.addEventListener('click', async () => { updateState((state) => { state.ui.theme = state.ui.theme === 'dark' ? 'light' : 'dark'; }); await rerender('Тема обновлена'); }); }
function bindDrawers() { dom.openDrawerSidebar?.addEventListener('click', openDrawer); dom.closeDrawer?.addEventListener('click', closeDrawer); dom.drawerBackdrop?.addEventListener('click', closeDrawer); }
function bindApartmentSearch() { dom.apartmentSearch?.addEventListener('input', () => { updateState((state) => { state.ui.apartmentSearch = dom.apartmentSearch.value; }); render(); }); dom.apartmentsList?.addEventListener('click', async (event) => { const btn = event.target.closest('[data-apartment-id]'); if (!btn) return; updateState((state) => { state.activeApartmentId = btn.dataset.apartmentId; }); await rerender('Квартира переключена'); }); }
function bindFinanceFilters() { const updateFilters = async () => { updateState((state) => { state.ui.finance.apartmentFilter = dom.financeApartmentFilter.value; state.ui.finance.typeFilter = dom.financeTypeFilter.value; state.ui.finance.month = dom.financeMonthFilter.value || monthKey(new Date()); state.ui.finance.showOnlyPending = dom.financeOnlyPending.checked; }); await rerender('Фильтры обновлены'); }; [dom.financeApartmentFilter, dom.financeTypeFilter, dom.financeMonthFilter, dom.financeOnlyPending].forEach((el) => el?.addEventListener(el.type === 'checkbox' ? 'change' : 'input', updateFilters)); }
function bindFinanceModals() { dom.financeAddEntryBtn?.addEventListener('click', () => { dom.financeEntryApartment.value = currentApartment()?.id || ''; dom.financeEntryType.value = 'expense'; dom.financeEntrySource.value = 'manual'; openModal('financeEntryModal'); }); dom.cancelFinanceEntry?.addEventListener('click', () => closeModal('financeEntryModal')); dom.saveFinanceEntry?.addEventListener('click', async () => { addFinanceEntry({ apartmentId: dom.financeEntryApartment.value, type: dom.financeEntryType.value, category: dom.financeEntryCategory.value, title: dom.financeEntryTitle.value, amount: Number(dom.financeEntryAmount.value || 0), date: dom.financeEntryDate.value, notes: dom.financeEntryNotes.value, source: dom.financeEntrySource.value || 'manual', status: dom.financeEntryType.value === 'income' ? 'confirmed' : 'planned' }); closeModal('financeEntryModal'); await rerender('Финансовая запись добавлена'); }); dom.financeAddRecurringBtn?.addEventListener('click', () => { dom.recurringApartment.value = currentApartment()?.id || ''; openModal('recurringExpenseModal'); }); dom.cancelRecurringExpense?.addEventListener('click', () => closeModal('recurringExpenseModal')); dom.saveRecurringExpense?.addEventListener('click', async () => { addRecurringRule({ apartmentId: dom.recurringApartment.value, title: dom.recurringTitle.value, category: dom.recurringCategory.value, amount: Number(dom.recurringAmount.value || 0), dayOfMonth: Number(dom.recurringDayOfMonth.value || 1), startDate: dom.recurringStartDate.value, endDate: dom.recurringEndDate.value, notes: dom.recurringNotes.value, type: 'expense' }); closeModal('recurringExpenseModal'); await rerender('Регулярный расход создан'); }); dom.financeOpenWebhookHelpBtn?.addEventListener('click', () => openModal('financeWebhookModal')); dom.closeFinanceWebhookModal?.addEventListener('click', () => closeModal('financeWebhookModal')); }
function bindRealtyCalendarSync() { dom.financePullBookingsBtn?.addEventListener('click', async () => { try { const data = await syncRealtyCalendarBookings(); const bookings = Array.isArray(data?.bookings) ? data.bookings.map(normalizeRealtyCalendarBooking) : []; const added = importBookingsToFinance(bookings); await rerender(added.length ? `Импортировано бронирований: ${added.length}` : 'Новых бронирований нет'); } catch (error) { setStatus(`Ошибка синхронизации: ${error.message}`); } }); }
export function bindEvents() { bindDrawers(); bindTheme(); bindSectionNav(); bindApartmentSearch(); bindFinanceFilters(); bindFinanceModals(); bindRealtyCalendarSync(); updateState((state) => { if (!state.ui.finance.month) state.ui.finance.month = monthKey(new Date()); }); }
